object DependanciesVersions {
    const val JUNIT_VERSION = "4.13.2"
    const val EXT_JUNIT_VERSION = "1.1.3"
    const val ESPRESSO_CORE_VERSION = "3.4.0"
    const val CORE_KTX_VERSION = "1.8.0"
    const val APPCOMPACT_VERSION = "1.4.2"
    const val MATERIAL_VERSION = "1.6.1"
    const val CONSTRAINTLAYOUT_VERSION = "2.1.4"
    const val ROOM_VERSION = "2.4.2"
    const val RETROFIT_VERSION = "2.6.0"
    const val GSONGOOGLE_VERSION = "2.8.6"
    const val CONVERTERSCALER_VERSION = "2.1.0"
    const val BUILD_GRAGLE_VERSION = "7.0.3"
    const val KOTLIN_PLUGIN_VERSION = "1.6.10"
    const val HILT_PLUGIN_VERSION = "2.38.1"
    const val COROUTINES_VERSION = "1.6.4"
    const val NAVIGATION_VERSION = "2.5.0"
    const val MOCK_VERSION = "4.6.1"
}